services:
  - type: web
    name: hamrah
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn hamrah.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: DATABASE_URL
        fromDatabase:
          name: hamrah-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.com

databases:
  - name: hamrah-db
    databaseName: hamrah
    user: hamrah
    plan: free 