# Generated by Django 5.0.1 on 2025-03-22 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_storeadmin_storeuser'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'فروشنده', 'verbose_name_plural': 'فروشندگان'},
        ),
        migrations.AlterField(
            model_name='seller',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.store'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='seller',
            table='sellers',
        ),
    ]
